CREATE DATABASE RAPIDDOOLA ;
USE RAPIDDOOLA ;

CREATE TABLE DDRIVER

(
DRII_ID INT PRIMARY KEY,
DRII_NAME varchar(34) ,
DRII_MOBILENO int ,
CARR_NO varchar(20) ,
CARR_SITER varchar(20) ,
PAYMANTT_MODE varchar(20) ,
NUMBERR_OFSITER varchar(20) ,
PICUUPP_POINT varchar(25) ,
DROOPP_POINT varchar(30) ,
KILOMITER VARCHAR(22),
CHAA_RGE int ,
DATEE_TIME date ,
TRAVELINGG_TIME varchar(15) ,
OTPP_VARIFY int ,
SLOTT_CONDITION varchar(15)
) ;


INSERT INTO DDRIVER (DRII_ID, DRII_NAME, DRII_MOBILENO, CARR_NO, CARR_SITER, PAYMANTT_MODE, NUMBERR_OFSITER, PICUUPP_POINT, DROOPP_POINT, KILOMITER, 
CHAA_RGE, DATEE_TIME, TRAVELINGG_TIME, OTPP_VARIFY, SLOTT_CONDITION)
VALUES (111222333,"MANISH",	992462,"GJAL123","FOUR SEATER",	"CARD,UPI,QR","3PERSON","CHANDKHEDA","VASTRAL",
52,1300,"2023-03-15","1:10 HOUR",111222,"AVAILABLE" ) ;


CREATE TABLE CUSSTMOER
(
CUST_ID INT PRIMARY KEY,
CUST_NAME VARCHAR(15),
CUST_PHONE INT ,
OTP_VERFIY INT ,
CHAR_REI INT,
FOREIGN KEY CUSSTMOER(CUST_ID) REFERENCES DDRIVER(DRII_ID)
) ;

SELECT * FROM DDRIVER
INNER JOIN CUSSTMOER
ON DDRIVER.DRII_ID = CUSSTMOER.CUST_ID ;

SELECT * FROM DDRIVER
LEFT JOIN CUSSTMOER
ON DDRIVER.DRII_ID = CUSSTMOER.CUST_ID ;

SELECT * FROM DDRIVER
RIGHT JOIN CUSSTMOER
ON DDRIVER.DRII_ID = CUSSTMOER.CUST_ID ;


